### ISSUE TITLE
About Non-overlappingmaskingstrategy

### ISSUE THREAD

**Issue by huangbr** [ShenAoAO/MoleSG#1]
Hello, I did't find how to realize the Non-overlapping masking strategy in code, could you please point out where is the core code?Thank you!

**Comment by HA716** [comment]
论文中说需要原子索引对齐，在代码data_geometirc_maeratio.py中a[masked_atom_indices] = 0这行是默认了SMILES字符串中的token ID是按照分子中原子的顺序排列的吗？不太明白您如何实现smiles和graph的原子对齐？

期待您的回复，谢谢！
